apiVersion: v1
kind: Service
metadata:
  name: flux-balancer
  namespace: flux
  labels:
    app: flux-balancer
    job: balancer
spec:
  selector:
    app: flux-balancer
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-balancer
  namespace: flux
  labels:
    app: flux-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-balancer
  template:
    metadata:
      labels:
        app: flux-balancer
    spec:
      containers:
        - name: flux-balancer-container
          image: flux-balancer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: SERVICE_NAME
              value: "flux-balancer"
            - name: SERVICE_PORT
              value: "8090"
            - name: SERVICE_HOST
              value: "flux-balancer"
            - name: CONSUL_HTTP_ADDR
              value: "http://consul-server:8500"
            - name: TARGET_SERVICE_NAME
              value: "flux-backend"
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
